on:
  push:
#    tags:
#    - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push
      run: dotnet nuget push "nop77svk-*\bin\Release\*.nupkg" --skip-duplicate --source https://nuget.pkg.github.com/nop77svk/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
