on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        pwd
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Build
      run: |
        pwd
        dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: |
        pwd
        dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: |
        pwd
        dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
        rm -f analyzer-settings.*.nupkg
    - name: Push
      run: |
        pwd
        echo -------
        ls -al *.nupkg
        echo -------
        ls -al NoP77svk.*.nupkg
        echo -------
        ls -al NoP77svk.*.${VERSION}.nupkg
        echo -------
        dotnet nuget push ls -al NoP77svk.*.${VERSION}.nupkg --source https://nuget.pkg.github.com/nop77svk/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
